export const MOTIVATIONAL_QUOTES = [
  "The only bad workout is the one that didn't happen.",
  "Your body can stand almost anything. It's your mind that you have to convince.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "Take care of your body. It's the only place you have to live.",
  "Sweat is fat crying.",
  "What seems impossible today will one day become your warm-up.",
  "Don't stop when you're tired. Stop when you're done.",
  "A one-hour workout is 4% of your day. No excuses.",
  "Push harder than yesterday if you want a different tomorrow.",
  "It never gets easier, you just get stronger.",
  "Success starts with self-discipline.",
  "Wake up. Work out. Look kick-ass.",
  "Doubt me, hate me, you're the inspiration I need.",
  "Sore today, strong tomorrow.",
  "Making excuses burns zero calories per hour.",
  "Strive for progress, not perfection.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "To enjoy the glow of good health, you must exercise.",
  "If it doesn't challenge you, it doesn't change you.",
  "Fall in love with taking care of your body.",
  "The hard part isn't getting your body in shape. The hard part is getting your mind in shape.",
  "You don't have to be extreme, just consistent.",
  "Good things come to those who sweat.",
  "Your health is an investment, not an expense.",
  "Train insane or remain the same.",
  "Respect your body. It's the only one you get.",
  "Every workout brings you closer to your goals.",
  "Be stronger than your strongest excuse.",
  "Discipline is doing what you hate to do, but doing it like you love it.",
  "Don't wish for a good body, work for it.",
  "Small daily improvements are the key to staggering long-term results.",
  "Pain is temporary. Quitting lasts forever.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "You are entirely up to you. Make your body. Make your life.",
  "Hustle for that muscle.",
  "Nothing truly great ever came from a comfort zone.",
  "Rome wasn't built in a day, but they worked on it every single day.",
  "Your only limit is you.",
  "Slow progress is better than no progress.",
  "Action is the foundational key to all success.",
  "Believe in yourself and all that you are.",
  "Strength doesn't come from what you can do. It comes from overcoming the things you once couldn't.",
  "Do something today that your future self will thank you for.",
  "The difference between the impossible and the possible lies in a person's determination.",
  "Don't limit your challenges, challenge your limits.",
  "It comes down to one simple thing: How bad do you want it?",
  "Willpower is like a muscle. The more you use it, the stronger it gets.",
  "Focus on your health, not your weight.",
  "A champion is someone who gets up when they can't.",
  "Clear your mind of can't.",
  "You don't get what you wish for, you get what you work for.",
  "Turn your setbacks into comebacks.",
  "The groundwork of all happiness is health.",
  "Keep your squats low and your standards high.",
  "Sweat is just your fat crying.",
  "Train like a beast, look like a beauty.",
  "When you feel like quitting, think about why you started.",
  "Blood, sweat, and respect. First two you give, last one you earn.",
  "No pain, no gain. Shut up and train.",
  "Excuses don't build muscle.",
  "The mirror is your competition.",
  "If you still look cute after your workout, you didn't train hard enough.",
  "Make your sweat your signature.",
  "Stronger every day.",
  "Results happen over time, not overnight. Work hard, stay consistent.",
  "Eat clean, train dirty.",
  "I don't stop when I'm tired, I stop when I'm done.",
  "Lift heavy, love life.",
  "Prove them wrong.",
  "Your body hears everything your mind says. Stay positive.",
  "A healthy lifestyle is something you create, not something you find.",
  "Let exercise be your stress reliever.",
  "The hardest lift of all is lifting your butt off the couch.",
  "Commit to be fit.",
  "Fitness is not a destination, it's a way of life.",
  "You only get out what you put in.",
  "There is no magic pill. You have to put in the work.",
  "Fitness is like a relationship. You can't cheat and expect it to work.",
  "Your mind will quit a thousand times before your body will.",
  "Get comfortable with being uncomfortable.",
  "Embrace the struggle.",
  "Be the hardest worker in the room.",
  "Success is what comes after you stop making excuses.",
  "Let your results do the talking.",
  "Build the best version of you.",
  "Work hard in silence.",
  "Never give up on a dream just because of the time it will take.",
  "Health is wealth.",
  "Don't wait for inspiration, be the inspiration.",
  "Your future is created by what you do today.",
  "Make fitness a priority.",
  "Be savage, not average.",
  "Don't count the days, make the days count.",
  "You're only one workout away from a good mood.",
  "Keep pushing, you're almost there.",
  "Great things never come from comfort zones.",
  "You are stronger than you think.",
  "Focus, execute, achieve.",
  "Sweat, smile, and repeat.",
  "Own your morning, elevate your life."
];